//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereIsPoliceman.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhereIsPoliceman.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МТС                 112
        ///
        ///Билайн            002
        ///
        ///Мегафон          02 (или 020)
        ///
        ///Скайлинк         02
        ///
        ///Tele2 Россия    020
        ///
        ///НСС                  02 (или 020)
        ///
        ///Сотел               112
        ///
        ///ETK                  112.
        /// </summary>
        public static string ekstrennnye_telefony_policii {
            get {
                return ResourceManager.GetString("ekstrennnye_telefony_policii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Определение функций полицейских может существенно различаться в разных странах. Практически всегда категорию «полицейская деятельностью» формируют криминальная полиция, дорожная и патрульная полиция. Именно эти три вида деятельности рассматриваются как полицейские в России и, следовательно, на их основании рассчитывается численность полицейских сил в России.
        ///
        ///Во многих странах в число полицейских входят также пограничные службы (исключение — Россия, Литва, Польша, Великобритания, Финляндия и Швеция). В чи [rest of string was truncated]&quot;;.
        /// </summary>
        public static string funkcii_policii_i_chislennost_policejskih {
            get {
                return ResourceManager.GetString("funkcii_policii_i_chislennost_policejskih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мировой опыт показывает, что взаимодействие полиции и общества - довольно сложный, порой весьма противоречивый процесс. Однако, в условиях быстро меняющегося мира и глобализации всех сторон жизнедеятельности человека – это, возможно, единственный инструмент, позволяющий эффективно противостоять современной преступности.
        ///
        ///В традиционном понимании, использовавшемся в XIX-XX веках, исключительным предназначением полиции является правоохранительная деятельность, предполагающая борьбу с преступностью и операти [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InfoPartners {
            get {
                return ResourceManager.GetString("InfoPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные направления деятельности полиции:
        ///1) защита личности, общества, государства от противоправных посягательств;
        ///
        ///2) предупреждение и пресечение преступлений и административных правонарушений;
        ///
        ///3) выявление и раскрытие преступлений, производство дознания по уголовным делам;
        ///
        ///4) розыск лиц;
        ///
        ///5) производство по делам об административных правонарушениях, исполнение административных наказаний;
        ///
        ///6) обеспечение правопорядка в общественных местах;
        ///
        ///7) обеспечение безопасности дорожного движения;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string napravleniya_deyatelnosti_i_obyazannosti_policii {
            get {
                return ResourceManager.GetString("napravleniya_deyatelnosti_i_obyazannosti_policii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полиция является составной частью системы МВД РФ. Полиция предназначена для защиты жизни, здоровья, прав и свобод граждан, для противодействия преступности, охраны общественного порядка, собственности и для обеспечения общественной безопасности.
        ///
        ///Руководство всей полицией в РФ осуществляет Министр внутренних дел.
        ///Министр внутренних дел подотчетен Президенту РФ; нижестоящие территориальные подразделения подотчетны вышестоящим территориальным подразделениям и не несут ответственности перед местными органам [rest of string was truncated]&quot;;.
        /// </summary>
        public static string organizaciyainaznacheniepolicii {
            get {
                return ResourceManager.GetString("organizaciyainaznacheniepolicii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете скачать памятки, разработанные полицейскими для граждан:
        /// 
        ///
        ///Памятка МВД: Как не стать жертвой мошенников
        ///
        ///Памятка МВД: Осторожно: Торговля людьми - как не стать жертвой
        ///
        ///Памятка МВД: Экономическая безопасность: Как не стать жертвой аферистов
        ///
        ///Памятка МВД: По общению с полицией на основе закона «О полиции»
        ///
        ///Памятка МВД: Управление &quot;К&quot; о мошенничестве в Интернет, по телефону и с банковскими картами
        ///
        ///Памятка МВД: Полиция детям (в виде увлекательных комиксов).
        /// </summary>
        public static string pamyatki_policii_grazhdanam_kak_ne_stat_zhertvoj {
            get {
                return ResourceManager.GetString("pamyatki_policii_grazhdanam_kak_ne_stat_zhertvoj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 января - День делопроизводственной службы МВД России (с 1804 г.)
        ///27 января - День печати МВД (с 1804 г.)
        ///12 февраля - День милиции общественной безопасности (МОБ)
        ///18 февраля - День транспортной милиции
        ///28 февраля - День образования инспекции по личному составу в системе МВД России
        ///1 марта - День Экспертно-криминалистической службы
        ///3 марта - День морских частей внутренних войск МВД России
        ///16 марта - День службы по борьбе с экономическими преступлениями (ранее ОБХСС)
        ///27 марта - День внутренних войс [rest of string was truncated]&quot;;.
        /// </summary>
        public static string prazdniki_mvd {
            get {
                return ResourceManager.GetString("prazdniki_mvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Сотрудник полиции имеет право лично или в составе подразделения (группы) применять специальные средства в следующих случаях:
        ///
        ///1) для отражения нападения на гражданина или сотрудника полиции;
        ///
        ///2) для пресечения преступления или административного правонарушения;
        ///
        ///3) для пресечения сопротивления, оказываемого сотруднику полиции;
        ///
        ///4) для задержания лица, застигнутого при совершении преступления и пытающегося скрыться;
        ///
        ///5) для задержания лица, если это лицо может оказать вооруженное сопротивление;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string specialnye_sredstva_policii {
            get {
                return ResourceManager.GetString("specialnye_sredstva_policii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cтруктура подразделений полиции
        ///На базе основных направлений деятельности и обязанностей полиции типичная структура подразделений полиции (на конкретном примере одного из регионов РФ – Главное управление МВД России по Челябинской области - http://74.mvd.ru/gumvd/structure/police/) выглядит следующим образом:
        ///
        ///Управление уголовного розыска
        ///Бюро регистрации несчастных случаев
        ///Центр по противодействию экстремизму
        ///Оперативно-розыскная часть (ОРЧ) по обеспечению безопасности лиц, подлежащих государственной [rest of string was truncated]&quot;;.
        /// </summary>
        public static string struktura_podrazdelenij_policii {
            get {
                return ResourceManager.GetString("struktura_podrazdelenij_policii", resourceCulture);
            }
        }
    }
}
